Non-generic MapComposite fails because CompositeTypeHandlerFactory is not public so we need to include NonPublic
System.MissingMethodException: 'Constructor on type 'Npgsql.TypeHandlers.CompositeHandlers.CompositeTypeHandlerFactory`1[[...type info...]]' not found.'